FROM ubuntu:jammy

RUN apt-get update \
    && apt-get install -y openjdk-11-jdk wget software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y python3.10 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

ENV SPARK_VERSION=3.5.1
ENV HADOOP_VERSION=3
#ENV SCALA_VERSION=2.13

# Example: https://downloads.apache.org/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz

RUN wget -qO- https://downloads.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz | tar zx -C /opt \
    && ln -s /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark \
    && rm -rf /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/examples

ENV SPARK_HOME /opt/spark
ENV PATH $SPARK_HOME/bin:$PATH

RUN echo '#!/bin/bash' > /opt/startup-master.sh && \
    echo '/opt/spark/sbin/start-master.sh' >> /opt/startup-master.sh && \
    echo 'tail -f /dev/null' >> /opt/startup-master.sh && \
    chmod +x /opt/startup-master.sh

RUN echo '#!/bin/bash' > /opt/startup-worker.sh && \
    echo '/opt/spark/sbin/start-worker.sh spark://spark-master:7077 --webui-port "$WEBUI_PORT" --memory "$WRK_MEMORY" --cores "$WRK_CORES"' >> /opt/startup-worker.sh && \
    echo 'tail -f /dev/null' >> /opt/startup-worker.sh && \
    chmod +x /opt/startup-worker.sh

EXPOSE 8080 7077 4040 6066
